package org.cagrid.introduce.tutorial.stockmanager.portfolio.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface StockPortfolioManagerConstantsBase {
	public static final String SERVICE_NS = "http://stockmanager.tutorial.introduce.cagrid.org/StockManager/Portfolio";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "StockPortfolioManagerKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "StockPortfolioManagerResourceProperties");
	public static final QName PORTFOLIO = new QName("http://tools.tutorial.introduce.cagrid.org/StockTools", "Portfolio");
	public static final QName CURRENTTIME = new QName("http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd", "CurrentTime");
	public static final QName TERMINATIONTIME = new QName("http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd", "TerminationTime");
	
}
