package org.cagrid.introduce.tutorial.stockmanager.portfolio.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public interface StockPortfolioManagerI {

  /**
   * Add a set of stock symbols to an existing Portfolio via Transfer
   *
   */
  public org.cagrid.transfer.context.stubs.types.TransferServiceContextReference addPortfolioSymbols() throws RemoteException ;

  /**
   * adds a stock to monitor in this portfolio
   *
   * @param symbol
   */
  public void addStock(java.lang.String symbol) throws RemoteException ;

  /**
   * returns the current stock quotes for the portfolio
   *
   */
  public org.cagrid.introduce.tutorial.tools.beans.PortfolioInstance getPortfolioQuote() throws RemoteException ;

  /**
   * Enumerate over stocks in the portfolio
   *
   * @throws PortfolioEnumerationException
   *	
   */
  public gov.nih.nci.cagrid.enumeration.stubs.response.EnumerationResponseContainer enumerateStocks() throws RemoteException, org.cagrid.introduce.tutorial.stockmanager.portfolio.stubs.types.PortfolioEnumerationException ;

  public org.oasis.wsrf.lifetime.DestroyResponse destroy(org.oasis.wsrf.lifetime.Destroy params) throws RemoteException ;

  public org.oasis.wsrf.lifetime.SetTerminationTimeResponse setTerminationTime(org.oasis.wsrf.lifetime.SetTerminationTime params) throws RemoteException ;

  public org.oasis.wsn.SubscribeResponse subscribe(org.oasis.wsn.Subscribe params) throws RemoteException ;

}

