package org.cagrid.demo.photosharing.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface PhotoSharingConstantsBase {
	public static final String SERVICE_NS = "http://photosharing.demo.cagrid.org/PhotoSharing";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "PhotoSharingKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "PhotoSharingResourceProperties");
	
}
