package org.cagrid.introduce.tutorial.stockmanager.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface StockManagerConstantsBase {
	public static final String SERVICE_NS = "http://stockmanager.tutorial.introduce.cagrid.org/StockManager";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "StockManagerKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "StockManagerResourceProperties");
	public static final QName SERVICEMETADATA = new QName("gme://caGrid.caBIG/1.0/gov.nih.nci.cagrid.metadata", "ServiceMetadata");
	
}
