package org.cagrid.introduce.tutorial.stockmanager.service;

import gov.nih.nci.cagrid.introduce.servicetools.ServiceConfiguration;

import org.globus.wsrf.config.ContainerConfig;
import java.io.File;
import javax.naming.InitialContext;

import org.apache.axis.MessageContext;
import org.globus.wsrf.Constants;


/** 
 * DO NOT EDIT:  This class is autogenerated!
 * 
 * This class holds all service properties which were defined for the service to have
 * access to.
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class StockManagerConfiguration implements ServiceConfiguration {

	public static StockManagerConfiguration  configuration = null;
    public String etcDirectoryPath;
    	
	public static StockManagerConfiguration getConfiguration() throws Exception {
		if (StockManagerConfiguration.configuration != null) {
			return StockManagerConfiguration.configuration;
		}
		MessageContext ctx = MessageContext.getCurrentContext();

		String servicePath = ctx.getTargetService();

		String jndiName = Constants.JNDI_SERVICES_BASE_NAME + servicePath + "/serviceconfiguration";
		try {
			javax.naming.Context initialContext = new InitialContext();
			StockManagerConfiguration.configuration = (StockManagerConfiguration) initialContext.lookup(jndiName);
		} catch (Exception e) {
			throw new Exception("Unable to instantiate service configuration.", e);
		}

		return StockManagerConfiguration.configuration;
	}
	

	
	private String caGridWsEnumeration_iterImplType;
	
	
    public String getEtcDirectoryPath() {
		return ContainerConfig.getBaseDirectory() + File.separator + etcDirectoryPath;
	}
	
	public void setEtcDirectoryPath(String etcDirectoryPath) {
		this.etcDirectoryPath = etcDirectoryPath;
	}


	
	public String getCaGridWsEnumeration_iterImplType() {
		return caGridWsEnumeration_iterImplType;
	}
	
	
	public void setCaGridWsEnumeration_iterImplType(String caGridWsEnumeration_iterImplType) {
		this.caGridWsEnumeration_iterImplType = caGridWsEnumeration_iterImplType;
	}

	
}
