package org.cagrid.introduce.tutorial.stockmanager.portfolio.service.globus;

import org.cagrid.introduce.tutorial.stockmanager.portfolio.service.StockPortfolioManagerImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the StockManagerImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class StockPortfolioManagerProviderImpl{
	
	StockPortfolioManagerImpl impl;
	
	public StockPortfolioManagerProviderImpl() throws RemoteException {
		impl = new StockPortfolioManagerImpl();
	}
	

    public org.cagrid.introduce.tutorial.stockmanager.portfolio.stubs.AddStockResponse addStock(org.cagrid.introduce.tutorial.stockmanager.portfolio.stubs.AddStockRequest params) throws RemoteException {
    org.cagrid.introduce.tutorial.stockmanager.portfolio.stubs.AddStockResponse boxedResult = new org.cagrid.introduce.tutorial.stockmanager.portfolio.stubs.AddStockResponse();
    impl.addStock(params.getSymbol().getSymbol());
    return boxedResult;
  }

    public org.cagrid.introduce.tutorial.stockmanager.portfolio.stubs.GetPortfolioQuoteResponse getPortfolioQuote(org.cagrid.introduce.tutorial.stockmanager.portfolio.stubs.GetPortfolioQuoteRequest params) throws RemoteException {
    org.cagrid.introduce.tutorial.stockmanager.portfolio.stubs.GetPortfolioQuoteResponse boxedResult = new org.cagrid.introduce.tutorial.stockmanager.portfolio.stubs.GetPortfolioQuoteResponse();
    boxedResult.setPortfolioInstance(impl.getPortfolioQuote());
    return boxedResult;
  }

    public org.cagrid.introduce.tutorial.stockmanager.portfolio.stubs.EnumerateStocksResponse enumerateStocks(org.cagrid.introduce.tutorial.stockmanager.portfolio.stubs.EnumerateStocksRequest params) throws RemoteException, org.cagrid.introduce.tutorial.stockmanager.portfolio.stubs.types.PortfolioEnumerationException {
    org.cagrid.introduce.tutorial.stockmanager.portfolio.stubs.EnumerateStocksResponse boxedResult = new org.cagrid.introduce.tutorial.stockmanager.portfolio.stubs.EnumerateStocksResponse();
    boxedResult.setEnumerationResponseContainer(impl.enumerateStocks());
    return boxedResult;
  }

}
