package org.cagrid.demo.photosharing.gallery.service.globus;


import java.rmi.RemoteException;
import java.util.HashMap;
import java.util.Map;
import java.io.File;
import javax.security.auth.Subject;
import javax.xml.namespace.QName;
import javax.xml.rpc.handler.MessageContext;

import gov.nih.nci.cagrid.introduce.servicetools.security.AuthorizationExtension;
import org.globus.wsrf.impl.security.authorization.exceptions.AuthorizationException;
import org.globus.wsrf.impl.security.authorization.exceptions.CloseException;
import org.globus.wsrf.impl.security.authorization.exceptions.InitializeException;
import org.globus.wsrf.impl.security.authorization.exceptions.InvalidPolicyException;
import org.globus.wsrf.security.authorization.PDP;
import org.globus.wsrf.security.authorization.PDPConfig;
import org.globus.wsrf.config.ContainerConfig;
import org.w3c.dom.Node;


/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This is a PDP for use with the globus authorization callout.
 * This class will have a authorize method for each method on this grid service.
 * The method is responsibe for making any authorization callouts required to satisfy the 
 * authorization requirements placed on each method call.  Each method will either return
 * apon a successful authorization or will throw an exception apon a failed authorization.
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class GalleryAuthorization implements PDP {

	public static final String SERVICE_NAMESPACE = "http://photosharing.demo.cagrid.org/PhotoSharing/Gallery";
	
	Map authorizationClassMap = new HashMap();
	
	
	public GalleryAuthorization() {
	}
	
	protected String getServiceNamespace(){
		return SERVICE_NAMESPACE;
	}
	
	public static String getCallerIdentity() {
		String caller = org.globus.wsrf.security.SecurityManager.getManager().getCaller();
		if ((caller == null) || (caller.equals("<anonymous>"))) {
			return null;
		} else {
			return caller;
		}
	}
					
	public void authorizeGetServiceSecurityMetadata(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeDestroy(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
		// authorization using service authorization from the enforce_auth extension
		((AuthorizationExtension)authorizationClassMap.get("enforce_auth")).authorizeService(peerSubject,context,operation);
		 	  
	}
	   				
	public void authorizeSetTerminationTime(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
		// authorization using service authorization from the enforce_auth extension
		((AuthorizationExtension)authorizationClassMap.get("enforce_auth")).authorizeService(peerSubject,context,operation);
		 	  
	}
	   				
	public void authorizeAddImage(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
		// authorization using service authorization from the enforce_auth extension
		((AuthorizationExtension)authorizationClassMap.get("enforce_auth")).authorizeService(peerSubject,context,operation);
		 	  
	}
	   				
	public void authorizeListImages(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
		// authorization using service authorization from the enforce_auth extension
		((AuthorizationExtension)authorizationClassMap.get("enforce_auth")).authorizeService(peerSubject,context,operation);
		 	  
	}
	   				
	public void authorizeGetImage(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
		// authorization using service authorization from the enforce_auth extension
		((AuthorizationExtension)authorizationClassMap.get("enforce_auth")).authorizeService(peerSubject,context,operation);
		 	  
	}
	   				
	public void authorizeGrantViewGalleryPrivileges(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
		// authorization using service authorization from the enforce_auth extension
		((AuthorizationExtension)authorizationClassMap.get("enforce_auth")).authorizeService(peerSubject,context,operation);
		 	  
	}
	   				
	public void authorizeRevokeViewGalleryPrivileges(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
		// authorization using service authorization from the enforce_auth extension
		((AuthorizationExtension)authorizationClassMap.get("enforce_auth")).authorizeService(peerSubject,context,operation);
		 	  
	}
	   				
	public void authorizeGrantAddImagePrivileges(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
		// authorization using service authorization from the enforce_auth extension
		((AuthorizationExtension)authorizationClassMap.get("enforce_auth")).authorizeService(peerSubject,context,operation);
		 	  
	}
	   				
	public void authorizeRevokeAddImagePrivileges(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
		// authorization using service authorization from the enforce_auth extension
		((AuthorizationExtension)authorizationClassMap.get("enforce_auth")).authorizeService(peerSubject,context,operation);
		 	  
	}
	   				
	public void authorizeGrantImageRetrievalPrivileges(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
		// authorization using service authorization from the enforce_auth extension
		((AuthorizationExtension)authorizationClassMap.get("enforce_auth")).authorizeService(peerSubject,context,operation);
		 	  
	}
	   				
	public void authorizeRevokeImageRetrievalPrivileges(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
		// authorization using service authorization from the enforce_auth extension
		((AuthorizationExtension)authorizationClassMap.get("enforce_auth")).authorizeService(peerSubject,context,operation);
		 	  
	}
	   				
	public void authorizeGetGalleryName(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
		// authorization using service authorization from the enforce_auth extension
		((AuthorizationExtension)authorizationClassMap.get("enforce_auth")).authorizeService(peerSubject,context,operation);
		 	  
	}
	   
	
	public boolean isPermitted(Subject peerSubject, MessageContext context, QName operation)
		throws AuthorizationException {
		
		if(!operation.getNamespaceURI().equals(getServiceNamespace())){
		  return false;
		}
		if(operation.getLocalPart().equals("getServiceSecurityMetadata")){
			authorizeGetServiceSecurityMetadata(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("destroy")){
			authorizeDestroy(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("setTerminationTime")){
			authorizeSetTerminationTime(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("addImage")){
			authorizeAddImage(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("listImages")){
			authorizeListImages(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("getImage")){
			authorizeGetImage(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("grantViewGalleryPrivileges")){
			authorizeGrantViewGalleryPrivileges(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("revokeViewGalleryPrivileges")){
			authorizeRevokeViewGalleryPrivileges(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("grantAddImagePrivileges")){
			authorizeGrantAddImagePrivileges(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("revokeAddImagePrivileges")){
			authorizeRevokeAddImagePrivileges(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("grantImageRetrievalPrivileges")){
			authorizeGrantImageRetrievalPrivileges(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("revokeImageRetrievalPrivileges")){
			authorizeRevokeImageRetrievalPrivileges(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("getGalleryName")){
			authorizeGetGalleryName(peerSubject, context, operation);
			return true;
		} 		
		return false;
	}
	

	public Node getPolicy(Node query) throws InvalidPolicyException {
		return null;
	}


	public String[] getPolicyNames() {
		return null;
	}


	public Node setPolicy(Node policy) throws InvalidPolicyException {
		return null;
	}


	public void close() throws CloseException {


	}


	public void initialize(PDPConfig config, String name, String id) throws InitializeException {
    	try{
    		String serviceName = (String)config.getProperty(name, "serviceName");
    	    String etcPath = ContainerConfig.getBaseDirectory() + File.separator + (String)config.getProperty(name, "etcDirectoryPath");

    	 
	   		authorizationClassMap.put("enforce_auth",Class.forName("org.cagrid.enforce.authorization.extension.service.EnforceAuthorization").newInstance());
			((AuthorizationExtension)authorizationClassMap.get("enforce_auth")).initialize(serviceName, etcPath);
			
    	} catch (Exception e){
        	throw new InitializeException(e.getMessage(),e);
		}
	}
	
	
}
