package org.cagrid.introduce.tutorial.stockmanager.service.globus;

import org.cagrid.introduce.tutorial.stockmanager.service.StockManagerImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the StockManagerImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class StockManagerProviderImpl{
	
	StockManagerImpl impl;
	
	public StockManagerProviderImpl() throws RemoteException {
		impl = new StockManagerImpl();
	}
	

    public org.cagrid.introduce.tutorial.stockmanager.stubs.GetQuoteResponse getQuote(org.cagrid.introduce.tutorial.stockmanager.stubs.GetQuoteRequest params) throws RemoteException {
    org.cagrid.introduce.tutorial.stockmanager.stubs.GetQuoteResponse boxedResult = new org.cagrid.introduce.tutorial.stockmanager.stubs.GetQuoteResponse();
    boxedResult.setQuote(impl.getQuote(params.getSymbol().getSymbol()));
    return boxedResult;
  }

    public org.cagrid.introduce.tutorial.stockmanager.stubs.GetChartResponse getChart(org.cagrid.introduce.tutorial.stockmanager.stubs.GetChartRequest params) throws RemoteException {
    org.cagrid.introduce.tutorial.stockmanager.stubs.GetChartResponse boxedResult = new org.cagrid.introduce.tutorial.stockmanager.stubs.GetChartResponse();
    boxedResult.setTransferServiceContextReference(impl.getChart(params.getSymbol().getSymbol()));
    return boxedResult;
  }

    public org.cagrid.introduce.tutorial.stockmanager.stubs.CreatePortfolioResponse createPortfolio(org.cagrid.introduce.tutorial.stockmanager.stubs.CreatePortfolioRequest params) throws RemoteException {
    org.cagrid.introduce.tutorial.stockmanager.stubs.CreatePortfolioResponse boxedResult = new org.cagrid.introduce.tutorial.stockmanager.stubs.CreatePortfolioResponse();
    boxedResult.setStockPortfolioManagerReference(impl.createPortfolio(params.getPortfolioName()));
    return boxedResult;
  }

}
