package org.cagrid.introduce.tutorial.stockmanager.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public interface StockManagerI {

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException ;

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException ;

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException ;

  /**
   * returns a stock quote for a given symbol
   *
   * @param symbol
   */
  public org.cagrid.introduce.tutorial.tools.beans.Quote getQuote(java.lang.String symbol) throws RemoteException ;

  /**
   * Retrieve a stock chart for a given symbol
   *
   * @param symbol
   */
  public org.cagrid.transfer.context.stubs.types.TransferServiceContextReference getChart(java.lang.String symbol) throws RemoteException ;

  /**
   * Create a new portfolio instance
   *
   * @param portfolioName
   */
  public org.cagrid.introduce.tutorial.stockmanager.portfolio.client.StockPortfolioManagerClient createPortfolio(java.lang.String portfolioName) throws RemoteException, org.apache.axis.types.URI.MalformedURIException ;

}

